CREATE TABLE IF NOT EXISTS articles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT
);

CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

INSERT INTO articles (title, content) VALUES
    ('最初', 'これは最初の記事です。'),
    ('二番目', 'これは二番目の記事です。'),
    ('三番目', 'これは三番目の記事です。');

INSERT INTO users (username, password) VALUES
    ('admin', 'password');