CREATE TABLE articles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT
);

INSERT INTO articles (title, content) VALUES
    ('最初', 'これは最初の記事です。'),
    ('二番目', 'これは二番目の記事です。'),
    ('三番目', 'これは三番目の記事です。');