name: Run Workflow

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  # 1番目：テストの呼び出し
  call-test-workflow:
    uses: ./.github/workflows/test.yml

  # 2番目：デプロイの呼び出し
  call-deploy-workflow:
    needs: call-test-workflow  # テストが成功した時のみ実行する
    uses: ./.github/workflows/deploy.yml
    secrets: inherit  # 親リポジトリのSecretsを子に引き継ぐ